
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import 'militaryUnit.sol';

// This is class that describes you smart contract.
contract archer {

    uint public powerAttack;
    uint public powerProtection;
    uint public health;

    constructor(uint _powerAttack, uint _powerProtection, uint _health) public {
        tvm.accept();
        powerAttack = _powerAttack;
        powerProtection = _powerProtection;
        health = _health;

    }
/*
    function sendValues(militaryUnit militaryUnitAddress) public {
        tvm.accept();
        militaryUnitAddress.attack(this);
    }
*/
}

//signer1  22d4285e31b53ba3115b00cec6f4296c6b03f0e0cf56730ee0f236c904abee6d

//archer signer1 0:c2031bd87ac9baad0291550ed7e72dcd7e3247b6833e7dd58f14c4d5469d9f88
//unit 0:9b6823014e44246949fd1f1696cb60dcf337cbecd5e250c37e14d9d00530011c

//signer2   4ecf2661f633d7dc40dfa5b964605e24d0f3d50e7dc4a929a2c46297a9f31d80
//owner_keys (D)  04145a9444e9604e7d90e483a73958f3395be5d74c7f4660f990e1f6e11e70f5

// archer owner 0:912d1e142a7f60ba9f104f807dabe9af5d3776636adae9577b70eb18f7b2f717