
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;


interface gameObject {
    function getValuesAttacking(int _powerAttack, int _powerProtection, int _health) external;
    function getValuesAttacked(int _powerAttack, int _powerProtection, int _health) external;

    function attack(address addressAttacked) external;
}