
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract warrior {

    uint public powerAttack;
    uint public powerProtection;

    constructor(uint _powerAttack, uint _powerProtection) public {
        tvm.accept();
        powerAttack = _powerAttack;
        powerProtection = _powerProtection;

    }

}